export const CREATE_CONTACT_LOADING = "REGISTER_LOADING";

export const CREATE_CONTACT_SUCCESS = "REGISTER_SUCCESS";

export const CREATE_CONTACT_ERROR = "REGISTER_ERRROR";

export const CLEAR_CREATE_CONTACT_STATE = 'CLEAR_REGISTER_STATE'; 

export const GET_CONTACTS_LOADING = "GET_CONTACTS_LOADING";

export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";

export const GET_CONTACTS_ERROR = "GET_CONTACTS_ERROR";

export const CLEAR_GET_CONTACT_STATE = 'CLEAR_GET_CONTACT_STATE'; 

export const GET_SINGLE_CONTACTS_LOADING = "GET_SINGLE_CONTACTS_LOADING";

export const GET_SINGLE_CONTACTS_SUCCESS = "GET_SINGLE_CONTACTS_SUCCESS";

export const GET_SINGLE_CONTACTS_ERROR = "GET_SINGLE_CONTACTS_ERROR";

export const CLEAR_GET_SINGLE_CONTACT_STATE = 'CLEAR_GET_SINGLE_CONTACT_STATE'; 

export const GET_SEARCH_CONTACTS_LOADING = "GET_SEARCH_CONTACTS_LOADING";

export const GET_SEARCH_CONTACTS_SUCCESS = "GET_SEARCH_CONTACTS_SUCCESS";

export const GET_SEARCH_CONTACTS_ERROR = "GET_SEARCH_CONTACTS_ERROR";

export const CLEAR_SEARCH_CONTACT_STATE = 'CLEAR_SEARCH_CONTACT_STATE'; 

export const UPDATE_CONTACT_LOADING = "UPDATE_CONTACT_LOADING";

export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";

export const UPDATE_CONTACT_ERROR = "UPDATE_CONTACT_ERROR";

export const CLEAR_UPDATE_CONTACT_STATE = 'CLEAR_UPDATE_CONTACT_STATE'; 

export const DELETE_CONTACT_LOADING = "DELETE_CONTACT_LOADING";

export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

export const DELETE_CONTACT_ERROR = "DELETE_CONTACT_ERROR";

export const CLEAR_DELETE_CONTACT_STATE = 'CLEAR_DELETE_CONTACT_STATE'; 

